### ISSUE TITLE
IX register protection ?

### ISSUE THREAD

**Issue by ericb59** [mvac7/SDCC_PT3player#1]
HEllo,

Thank you for this nice PT3 Replayer for SDCC.
I just have a question ...
I do not see IX Register protection (Push / Pop) inside the PT3Decode routine.
It may cause some troubles ? No ?

**Comment by mvac7** [comment]
Hi Eric!
I think I learned it by imitation. Looking at the assembly output of the SDCC compiler, I saw that in C functions that do not contain parameters, it does not add the save/recall instructions from IX to the Stack. 
In the tests it did not give me problems, but I am not sure if they are necessary. I am not an expert. ;)

**Comment by mvac7** [comment]
@ericb59 You are right. 
Corrected!
Thanks! :)
